### ISSUE TITLE
Pushing new commits to active app resets the data

### ISSUE THREAD

**Issue by alexbagirov** [gautamkrishnar/Anchor-CMS-openshift-quickstart#3] opened 2015-12-24 14:51 UTC
If I daploy an app, then add something to it's code, commit and send it again, I will see installation page again after it.

**Comment by gautamkrishnar** [comment] 2015-12-24 16:05
@alexbagirov  Its an @openshift issue: 
I hope that someone @openshift will comment on this

https://developers.openshift.com/en/managing-modifying-applications.html
https://forums.openshift.com/git-push-does-not-reflect-changes

**Comment by gautamkrishnar** [comment] 2015-12-24 16:10
You can still backup your app data by using any of the web file mangers by installing that into your app

**Comment by alexbagirov** [comment] 2015-12-24 16:31
@gautamkrishnar I don't understand how is it connected. There are a lot of deployed apps and quickstarts that continue  working after adding a commit so I think it can be fixed there.

**Comment by gautamkrishnar** [comment] 2015-12-25 06:01
ok @alexbagirov i will check,

**Comment by gautamkrishnar** [comment] 2015-12-26 10:27
@alexbagirov can you give me any of the example quickstart that retains data after pushing? Please comment the github url too

**Comment by alexbagirov** [comment] 2015-12-26 11:26
@gautamkrishnar Sure. Ghost, for example, keeps all you data after pushing and continue working after it.
https://github.com/openshift-quickstart/openshift-ghost-quickstart

**Comment by gautamkrishnar** [comment] 2015-12-26 11:31
Ok i will check that. Thanks a lot :+1:

**Comment by gautamkrishnar** [comment] 2015-12-26 11:35
![screenshot 90](https://cloud.githubusercontent.com/assets/8397274/12006204/d2ff3d6a-abf2-11e5-8642-9cb4fa777810.png)
This is what i need :smile:

**Comment by alexbagirov** [comment] 2015-12-26 11:38
Yes :smiley: 
That's because I've tried some other quickstarts and I remember that they were working fine always.

**Comment by gautamkrishnar** [comment] 2015-12-26 18:22
@alexbagirov Please check it again i think the issue is now fixed :smile:

**Comment by alexbagirov** [comment] 2015-12-26 19:42
Oh no...500 error.

**Comment by gautamkrishnar** [comment] 2015-12-26 19:55
@alexbagirov Will check that out

**Comment by gautamkrishnar** [comment] 2015-12-26 20:36
@alexbagirov its now fixed.
Thanks for helping out :dancer:  :smile:

**Comment by gautamkrishnar** [comment] 2015-12-26 21:20
Just closing this now..
will add more commits

**Comment by gautamkrishnar** [comment] 2015-12-26 22:00
@alexbagirov i think this issue wontfix.
Even though i had added all required directory persistent. its still not working. I will get in touch with the CMS devs to know more...
If you are a anchor CMS user, you can help me out: what are the directories written by anchor cms during installation?
For now i am closing this issue

**Closed as completed** 2015-12-26 22:01 UTC
Labels: bug, enhancement, wontfix
